/*
 * This file was generated by the Gradle 'init' task.
 */

rootProject.name = "advent-of-code"
//include(":advent-of-code-2021")
//include(":advent-of-code-2020")
//include(":advent-of-code-2023")
//include(":advent-of-code-2022")
include(":aoc-utils")
//include(":downloader")
//include(":advent-of-code-2019")
//include(":advent-of-code-2024")
//include(":aoc-runner")
