/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.hzt.quizzes.java-conventions")
}

dependencies {
    api("org.hzt.utils:core:1.0.5.22")
    api("org.hzt.utils:graph-utils:1.0.5.22")
    api(project(":aoc-utils"))
    testImplementation("org.junit.jupiter:junit-jupiter:5.11.3")
}

description = "Advent of Code 2020"
