/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.hzt.quizzes.java-conventions")
}

dependencies {
    api("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")
    api("org.jetbrains.kotlinx:kotlinx-collections-immutable:0.3.8")
    api(project(":aoc-utils"))
    api("org.hzt.utils:core:1.0.5.22")
}

description = "advent-of-code-2024"
