/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.hzt.quizzes.java-conventions")
}

dependencies {
    api("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")
    api("org.jetbrains:annotations:24.0.1")
    api("org.hzt.utils:core:1.0.5.22")
    api("org.hzt.utils:graph-utils:1.0.5.22")
    api(project(":aoc-utils"))
}

description = "Advent of Code 2022"
