name: advent_of_code_2023
description: A project to participate in advent od code
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.2

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.21.0
