/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.hzt.quizzes.java-conventions")
}

dependencies {
    api("org.jetbrains.kotlin:kotlin-stdlib:2.1.0")
    api("org.jetbrains:annotations:24.0.1")
}

description = "Advent of Code utilities"
