/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("org.hzt.quizzes.java-conventions")
}

dependencies {
    api(project(":advent-of-code-2019"))
    api(project(":advent-of-code-2020"))
    api(project(":advent-of-code-2021"))
    api(project(":advent-of-code-2022"))
    api(project(":advent-of-code-2023"))
}

description = "aoc-runner"
